version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./php:/var/www/html

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: proxecto
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contrasinal
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: